apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: us.gcr.io/howard-west/searchlite-backend:latest
          name: backend
          ports:
            - containerPort: 8080
              name: application
