import { Component } from '@angular/core';
import { Router } from '@angular/router';

//app-root component is automatically generated by the CLI
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  constructor(private _router: Router) {}

  navigateToAccount() {
    this._router.navigate(['/account']);
  }

  isAccountInfoPage(): boolean {
  	return window.location.href.includes('account');
  }
}
