apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 4200
      targetPort: 4200
      protocol: TCP
  type: LoadBalancer
  selector:
    role: frontend
    app: searchlite
